kind: Service
apiVersion: v1
metadata:
  name: backend-svc
  labels:
    app: crud-demo
spec:
  selector:
    app: crud-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  labels:
    app: crud-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-demo
  template:
    metadata:
      labels:
        app: crud-demo
    spec:
      containers:
      - name: crud-backend
        image: awingdev2020/crud-backend:$BUILD_NUMBER
        env:
        volumeMounts:
        - mountPath: "/etc/localtime"
          name: awingtimezone
      volumes:
        - name: awingtimezone
          hostPath:
            path: "/usr/share/zoneinfo/Asia/Ho_Chi_Minh"